before_script:
   - npm-cache install
job:
   script:
      - gulp
      - gulp build:zip
      - rsync -pva --exclude 'node_modules' --exclude 'assets/src' --exclude '.*' --exclude '.*/' ./dist/ deployer@demos.pixel2html.com:/home/deployer/www/demos/00042/000crossover-test/
      - "curl -X POST -F path=00042/000crossover-test http://deployer.pixel2html.com/html/demo_links_update"
